name: 'Publish to NPM'
description: 'Publish an npm package from a package.json'
inputs:
  gpg-private-key:
    description: GPG private key for signing the published artifacts
    required: true
  gpg-passphrase:
    description: Passphrase for the GPG key
    required: true
  nexus-username:
    description: Username (not email!) for your Nexus repository manager account
    required: true
  nexus-password:
    description: Password for your Nexus account
    required: true
  server-id:
    description: Nexus server id
    required: false
    default: ossrh
  maven-goals:
    description: Maven goals to run
    required: false
    default: clean deploy
  maven-profiles:
    description: Maven profiles
    required: false
    default: sign-source-javadoc
  working-directory:
    description: "Path within the repo to the folder where the pom.xml file lives"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: import GPG key
      run: |
        echo -e "${{ inputs.gpg-private-key }}" | gpg --batch --import --no-tty
        echo "hello world" > temp.txt
        gpg --detach-sig \
          --yes -v \
          --output=/dev/null \
          --pinentry-mode loopback \
          --passphrase "${{ inputs.gpg-passphrase }}" temp.txt
        rm temp.txt
      shell: bash
    - name: publish artefacts
      run: |
        echo "PWD:$(pwd)"
        dir=$(dirname $(realpath ${{ github.action_path }}))
        echo "DIR:$dir"
        mvn ${{ inputs.goals }} \
          --batch-mode \
          --settings $dir/settings.xml \
          --activate-profiles ${{ inputs.maven-profiles }} \
          -DskipTests=true
      shell: bash
      env:
        INPUT_SERVER_ID: ${{ inputs.server-id }}
        INPUT_NEXUS_USERNAME: ${{ inputs.nexus-username }}
        INPUT_NEXUS_PASSWORD: ${{ inputs.nexus-password }}
        INPUT_GPG_PASSPHRASE: ${{ inputs.gpg-passphrase }}
      working-directory: ${{ inputs.working-directory }}

branding:
  icon: package
  color: green
