name: 'Publish to NPM'
description: 'Publish an npm package from a package.json'
inputs:
  gpg-private-key:
    description: GPG private key for signing the published artifacts
    required: true
  gpg-passphrase:
    description: Passphrase for the GPG key
    required: true
  nexus-username:
    description: Username (not email!) for your Nexus repository manager account
    required: true
  nexus-password:
    description: Password for your Nexus account
    required: true
  goals:
    description: Maven goals to run
    required: false
    default: clean deploy
  working-directory:
    description: "Path within the repo to the folder where the pom.xml file lives"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: import GPG key
      run: |
        echo -e "${{ inputs.gpg-private-key }}" | gpg --batch --import --no-tty
        echo "hello world" > temp.txt
        gpg --detach-sig --yes -v --output=/dev/null --pinentry-mode loopback --passphrase "${{ inputs.gpg-passphrase }}" temp.txt
        rm temp.txt
      shell: bash
    - name: publish artefacts
      run: |
        mvn ${{ inputs.goals }} --batch-mode --activate-profiles sign-source-javadoc -DskipTests=true
      shell: bash
      working-directory: ${{ inputs.working-directory }}

branding:
  icon: package
  color: green
