name: Test

on:
  workflow_call:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - renovate/**

jobs:
  test-publish-mvn:
    name: It publishes Maven artefacts
    runs-on: ubuntu-latest
    environment: Publish to Nexus
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"
      - name: Set unique package version
        id: set-version
        run: |
          version=0.0.$GITHUB_RUN_NUMBER
          mvn versions:set -DnewVersion=$version -DgenerateBackupPoms=false
          echo "::set-output name=version::$version"
        working-directory: "test"
      - name: Test the action
        uses: ./
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          nexus-username: ${{ secrets.SONATYPE_USERNAME }}
          nexus-password: ${{ secrets.SONATYPE_PASSWORD }}
          working-directory: "test"
      - name: Assert that latest published package version is as expected
        timeout-minutes: 1
        run: |
          version=0.0.$GITHUB_RUN_NUMBER
          url=https://oss.sonatype.org/service/local/repositories/releases/content/io/cucumber/test-release-automation/$version/
          curl --verbose --fail $url
