name: Test

on:
  # Do not trigger on every change. Maven central has publishing limits.
  workflow_call:

permissions: {}

jobs:
  test-publish-mvn:
    name: It publishes Maven artefacts
    runs-on: ubuntu-latest
    environment: Publish to Nexus
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set unique package version
        id: set-version
        run: |
          version="0.0.$GITHUB_RUN_NUMBER"
          mvn versions:set -DnewVersion="$version" -DgenerateBackupPoms=false --batch-mode
          echo "version=$version" >> $GITHUB_OUTPUT
        working-directory: "test"
      - name: Test the action
        uses: ./
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          nexus-username: ${{ secrets.SONATYPE_USERNAME }}
          nexus-password: ${{ secrets.SONATYPE_PASSWORD }}
          working-directory: "test"
      - name: Assert that latest published package version is as expected
        timeout-minutes: 1
        # Don't use --verbose on curl. It will print the authorization header, base64 encoded so not masked by GitHub.
        run: |
          version="0.0.$GITHUB_RUN_NUMBER"
          url="https://central.sonatype.com/api/v1/publisher/published?namespace=io.cucumber&name=test-release-automation&version=$version"
          echo "Checking publishing $url"
          curl --fail \
            -u "${{ secrets.SONATYPE_USERNAME }}:${{ secrets.SONATYPE_PASSWORD }}" \
            -H 'accept: application/json' \
            "$url" \
          | jq '.published == true' \
          | grep -e '^true$'
          
          
            
